name: Continuous Integration

on:
  pull_request:
    branches: [master]
  workflow_dispatch: # Manually trigger workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Build Docker Image
        run: docker build -t combat-connect-app-dev .

      - name: Start Docker Containers
        run: |
          set -e
          docker-compose up -d || { echo 'Docker Compose failed.' ; exit 1; }

      - name: Run tests
        run: npm test

      - name: Run linter
        run: npm run lint

      - name: Stop Docker Containers
        run: docker-compose down