name: Continuous Integration

on:
  pull_request:
    branches: [master]
  workflow_dispatch: # Manually trigger workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Run tests
        run: npm test
        needs: Build application

      - name: Run linter
        run: npm run lint
        needs: Build application